####################################################################################################
##                                                                                                ##
##                                         File Information                                       ##
##                                                                                                ##
##  Plugin name: SuperiorSkyblock 2                                                               ##
##  Developer: Ome_R                                                                              ##
##  Language: Simplified Chinese                                                                  ##
##  Translator: Konsheng                                                                          ##
##  Translation time: 2022/6/28 GMT+8                                                             ##
##  Github: https://github.com/konsheng/SuperiorSkyblock2-Language                                ##
##  License: https://github.com/konsheng/SuperiorSkyblock2-Language/blob/main/LICENSE.md          ##
##                                                                                                ##
####################################################################################################

# Should missions be enabled on your server?
enabled: true

# Settings related to mission categories.
# A tutorial about configuring missions can be found here:
# https://wiki.bg-software.com/superiorskyblock/missions
categories:
  miner:
    name: '矿工'
    slot: 20

  slayer:
    name: '杀手'
    slot: 21

  farmer:
    name: '农夫'
    slot: 22

  fisherman:
    name: '渔夫'
    slot: 23

  explorer:
    name: '探险家'
    slot: 24

####################################################################################################
##                                                                                                ##
##                                         File Information                                       ##
##                                                                                                ##
##  Plugin name: SuperiorSkyblock 2                                                               ##
##  Developer: Ome_R                                                                              ##
##  Language: Simplified Chinese                                                                  ##
##  Translator: Konsheng                                                                          ##
##  Translation time: 2022/6/28 GMT+8                                                             ##
##  Github: https://github.com/konsheng/SuperiorSkyblock2-Language                                ##
##  License: https://github.com/konsheng/SuperiorSkyblock2-Language/blob/main/LICENSE.md          ##
##                                                                                                ##
####################################################################################################
