####################################################################################################
##                                                                                                ##
##                                         File Information                                       ##
##                                                                                                ##
##  Plugin name: SuperiorSkyblock 2                                                               ##
##  Developer: Ome_R                                                                              ##
##  Language: Simplified Chinese                                                                  ##
##  Translator: Konsheng                                                                          ##
##  Translation time: 2022/6/28 GMT+8                                                             ##
##  Github: https://github.com/konsheng/SuperiorSkyblock2-Language                                ##
##  License: https://github.com/konsheng/SuperiorSkyblock2-Language/blob/main/LICENSE.md          ##
##                                                                                                ##
####################################################################################################

title: '&8空岛设置'
previous-menu: true

pattern:
  - '$ $ $ $ $ $ $ $ $'
  - '$ @ @ @ @ @ @ @ $'
  - '$ @ @ @ @ @ @ @ $'
  - '$ @ @ @ @ @ @ @ $'
  - '$ @ @ @ @ @ @ @ $'
  - '$ $ % $ * $ ^ $ $'

slots: '@'
previous-page: '%'
current-page: '*'
next-page: '^'

items:
  '$':
    type: BLACK_STAINED_GLASS_PANE
    name: '&f'
  '%':
    type: PAPER
    name: '{0}上一页'
  '*':
    type: SUNFLOWER
    name: '&a当前页面'
    lore:
      - '&7Page {0}'
  '^':
    type: PAPER
    name: '{0}下一页'

settings:
  always_day:
    settings-enabled:
      type: YELLOW_TERRACOTTA
      name: '&6保持早晨'
      lore:
        - '&7将您的空岛时间保持早晨'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: YELLOW_TERRACOTTA
      name: '&6保持早晨'
      lore:
        - '&7将您的空岛时间保持早晨'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  always_middle_day:
    settings-enabled:
      type: ORANGE_TERRACOTTA
      name: '&6保持中午'
      lore:
        - '&7将您的空岛时间保持中午'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: ORANGE_TERRACOTTA
      name: '&6保持中午'
      lore:
        - '&7将您的空岛时间保持中午'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  always_night:
    settings-enabled:
      type: LIGHT_BLUE_TERRACOTTA
      name: '&6保持夜晚'
      lore:
        - '&7将您的空岛时间保持夜晚'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: LIGHT_BLUE_TERRACOTTA
      name: '&6保持夜晚'
      lore:
        - '&7将您的空岛时间保持夜晚'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  always_middle_night:
    settings-enabled:
      type: BLUE_TERRACOTTA
      name: '&6保持深夜'
      lore:
        - '&7将您的空岛时间保持深夜'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: BLUE_TERRACOTTA
      name: '&6保持深夜'
      lore:
        - '&7将您的空岛时间保持深夜'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  always_rain:
    settings-enabled:
      type: LILY_PAD
      name: '&6保持下雨'
      lore:
        - '&7将您的空岛天气保持下雨'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: LILY_PAD
      name: '&6保持下雨'
      lore:
        - '&7将您的空岛天气保持下雨'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  always_shiny:
    settings-enabled:
      type: DEAD_BUSH
      name: '&6保持晴天'
      lore:
        - '&7将您的空岛天气保持晴天'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: DEAD_BUSH
      name: '&6保持晴天'
      lore:
        - '&7将您的空岛天气保持晴天'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  creeper_explosion:
    settings-enabled:
      type: CREEPER_HEAD
      name: '&6苦力怕爆炸'
      lore:
        - '&7允许苦力怕在您的空岛上爆炸破坏方块'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: CREEPER_HEAD
      name: '&6苦力怕爆炸'
      lore:
        - '&7允许苦力怕在您的空岛上爆炸破坏方块'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  crops_growth:
    settings-enabled:
      type: WHEAT_SEEDS
      name: '&6农作物生长'
      lore:
        - '&7允许农作物在您的空岛上生长'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: WHEAT_SEEDS
      name: '&6作物生长'
      lore:
        - '&7允许农作物在您的空岛上生长'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  egg_lay:
    settings-enabled:
      type: EGG
      name: '&6鸡下蛋'
      lore:
        - '&7允许鸡在您的空岛上下蛋'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: EGG
      name: '&6鸡下蛋'
      lore:
        - '&7允许鸡在您的空岛上下蛋'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  enderman_grief:
    settings-enabled:
      type: ENDER_PEARL
      name: '&6末影人拾取方块'
      lore:
        - '&7允许末影人在您的空岛上拾取方块'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: ENDER_PEARL
      name: '&6末影人拾取方块'
      lore:
        - '&7允许末影人在您的空岛上拾取方块'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  fire_spread:
    settings-enabled:
      type: FLINT_AND_STEEL
      name: '&6火焰蔓延'
      lore:
        - '&7允许火焰在您的空岛上蔓延'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: FLINT_AND_STEEL
      name: '&6火焰蔓延'
      lore:
        - '&7允许火焰在您的空岛上蔓延'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  ghast_fireball:
    settings-enabled:
      type: FIRE_CHARGE
      name: '&6恶魂火球'
      lore:
        - '&7允许火球破坏您空岛上的方块'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: FIRE_CHARGE
      name: '&6恶魂火球'
      lore:
        - '&7允许火球破坏您空岛上的方块'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  lava_flow:
    settings-enabled:
      type: LAVA_BUCKET
      name: '&6岩浆流动'
      lore:
        - '&7允许岩浆在您的空岛上流动'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: LAVA_BUCKET
      name: '&6岩浆流动'
      lore:
        - '&7允许岩浆在您的空岛上流动'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  natural_animals_spawn:
    settings-enabled:
      type: PIG_SPAWN_EGG
      name: '&6自然动物生成'
      lore:
        - '&7允许动物在您的空岛上自然生成'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: PIG_SPAWN_EGG
      name: '&6自然动物生成'
      lore:
        - '&7允许动物在您的空岛上自然生成'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  natural_monster_spawn:
    settings-enabled:
      type: ZOMBIE_SPAWN_EGG
      name: '&6自然怪物生成'
      lore:
        - '&7允许怪物在您的空岛上自然生成'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: ZOMBIE_SPAWN_EGG
      name: '&6自然怪物生成'
      lore:
        - '&7允许怪物在您的空岛上自然生成'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  pvp:
    settings-enabled:
      type: DIAMOND_SWORD
      name: '&6PvP'
      lore:
        - '&7允许玩家在您的空岛上进行PvP'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: DIAMOND_SWORD
      name: '&6PvP'
      lore:
        - '&7允许玩家在您的空岛上进行PvP'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  spawner_animals_spawn:
    settings-enabled:
      type: SPAWNER
      name: '&6刷怪笼动物生成'
      lore:
        - '&7允许刷怪笼在您的空岛上生成动物'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: SPAWNER
      name: '&6刷怪笼动物生成'
      lore:
        - '&7允许刷怪笼在您的空岛上生成动物'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  spawner_monster_spawn:
    settings-enabled:
      type: SPAWNER
      name: '&6刷怪笼怪物生成'
      lore:
        - '&7允许刷怪笼在您的空岛上生成怪物'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: SPAWNER
      name: '&6刷怪笼怪物生成'
      lore:
        - '&7允许刷怪笼在您的空岛上生成怪物'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  tnt_explosion:
    settings-enabled:
      type: TNT
      name: '&6TNT爆炸'
      lore:
        - '&7允许TNT爆炸破坏您空岛上的方块'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: TNT
      name: '&6TNT爆炸'
      lore:
        - '&7允许TNT爆炸破坏您空岛上的方块'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  tree_growth:
    settings-enabled:
      type: OAK_SAPLING
      name: '&6树木生长'
      lore:
        - '&7允许树木在您的空岛上生长'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: OAK_SAPLING
      name: '&6树木生长'
      lore:
        - '&7允许树木在您的空岛上生长'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  water_flow:
    settings-enabled:
      type: WATER_BUCKET
      name: '&6水流动'
      lore:
        - '&7允许水在您的空岛上流动'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: WATER_BUCKET
      name: '&6水流动'
      lore:
        - '&7允许水在您的空岛上流动'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

  wither_explosion:
    settings-enabled:
      type: WITHER_SKELETON_SKULL
      name: '&6凋零爆炸'
      lore:
        - '&7允许凋零在您的空岛上爆炸破坏方块'
        - '&7当前状态: &a开启'
    settings-disabled:
      type: WITHER_SKELETON_SKULL
      name: '&6凋零爆炸'
      lore:
        - '&7允许凋零在您的空岛上爆炸破坏方块'
        - '&7当前状态: &c关闭'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2

####################################################################################################
##                                                                                                ##
##                                         File Information                                       ##
##                                                                                                ##
##  Plugin name: SuperiorSkyblock 2                                                               ##
##  Developer: Ome_R                                                                              ##
##  Language: Simplified Chinese                                                                  ##
##  Translator: Konsheng                                                                          ##
##  Translation time: 2022/6/28 GMT+8                                                             ##
##  Github: https://github.com/konsheng/SuperiorSkyblock2-Language                                ##
##  License: https://github.com/konsheng/SuperiorSkyblock2-Language/blob/main/LICENSE.md          ##
##                                                                                                ##
####################################################################################################
